# Generated by Django 4.0.6 on 2022-07-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_rename_first_name_patient_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=15)),
                ('patient_visit_date', models.FloatField()),
                ('patient_height_in_center_metres', models.FloatField()),
                ('patient_weight_in_kg', models.FloatField()),
                ('patient_Bmi', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
