# Generated by Django 4.0.6 on 2022-07-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_vital_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=25)),
                ('visit_date', models.DateField()),
                ('general_health', models.CharField(max_length=15)),
                ('comment', models.CharField(max_length=20)),
                ('weigth_choice', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=17, null=True)),
            ],
        ),
    ]
