# Generated by Django 4.0.6 on 2022-07-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_remove_visit_comment_visit_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='general_health',
        ),
        migrations.AddField(
            model_name='visit',
            name='general_heaith',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor')], max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
