# Generated by Django 4.0.6 on 2022-07-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_remove_visit_general_health_visit_general_heaith_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='general_heaith',
            new_name='general_health',
        ),
    ]
