# Generated by Django 4.0.6 on 2022-07-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_visit_general_health'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='general_health',
        ),
        migrations.AlterField(
            model_name='vital',
            name='patient_visit_date',
            field=models.DateField(),
        ),
    ]
