# Generated by Django 4.0.6 on 2022-07-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0013_visit_patient_general_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
