# Generated by Django 4.0.6 on 2022-07-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_alter_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
