# Generated by Django 4.0.6 on 2022-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0016_alter_vital_patient_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital',
            name='patient_Bmi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vital',
            name='patient_height_in_center_metres',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vital',
            name='patient_weight_in_kg',
            field=models.FloatField(),
        ),
    ]
