# Generated by Django 4.0.6 on 2022-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0018_remove_visit_patient_general_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='patient_general_health',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor')], max_length=17, null=True),
        ),
    ]
