# Generated by Django 4.0.6 on 2022-07-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0019_visit_patient_general_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
    ]
